services:
  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgres/data
      - ./data:/app/data
      - ./sql:/app/sql
    networks:
      - data-net
    environment:
      POSTGRES_DB: netflix-titles
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports: 
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U user -d netflix-titles"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  data-net:
    driver: bridge
    